gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: https://leon0322.github.io
author: Leon
highlighter: pygments
exclude: ["Rakefile", "CNAME", "README.md"]